using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace MediatRR.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class HandlerRegistrationGenerator : IIncrementalGenerator
{
    private const string RequestHandlerDefinition = "MediatRR.Contract.Messaging.IRequestHandler<TRequest, TResponse>";
    private const string StreamHandlerDefinition = "MediatRR.Contract.Messaging.IStreamRequestHandler<TRequest, TResponse>";
    private const string AddTransient = "            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registrations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null } or RecordDeclarationSyntax { BaseList: not null },
                static (syntaxContext, cancellationToken) => Transform(syntaxContext, cancellationToken))
            .Where(static registration => registration.HasValue)
            .Select(static (registration, _) => registration!.Value)
            .Collect();

        context.RegisterSourceOutput(registrations, static (productionContext, items) =>
            productionContext.AddSource("MediatRR.ServiceGenerator.g.cs", SourceText.From(Render(items), Encoding.UTF8)));
    }

    private static (string RequestLines, string StreamLines)? Transform(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.SemanticModel.GetDeclaredSymbol((TypeDeclarationSyntax)context.Node, cancellationToken) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.TypeKind != TypeKind.Class || symbol.IsAbstract || symbol.IsStatic || symbol.IsGenericType || !IsAccessibleFromAssembly(symbol))
        {
            return null;
        }

        var requestLines = new StringBuilder();
        var streamLines = new StringBuilder();
        foreach (var contract in symbol.AllInterfaces)
        {
            var definition = contract.OriginalDefinition.ToDisplayString();
            var target = definition == RequestHandlerDefinition ? requestLines
                : definition == StreamHandlerDefinition ? streamLines
                : null;
            if (target is null)
            {
                continue;
            }

            target.Append(AddTransient)
                .Append(contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append(", ")
                .Append(symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .AppendLine(">(services);");
        }

        if (requestLines.Length == 0 && streamLines.Length == 0)
        {
            return null;
        }

        return (requestLines.ToString(), streamLines.ToString());
    }

    private static bool IsAccessibleFromAssembly(INamedTypeSymbol symbol)
    {
        for (INamedTypeSymbol? current = symbol; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal))
            {
                return false;
            }
        }

        return true;
    }

    private static string Render(ImmutableArray<(string RequestLines, string StreamLines)> types)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace MediatRR.ServiceGenerator");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class SourceGeneratorInjectDependencies");
        builder.AppendLine("    {");
        AppendMethod(builder, "AutoRegisterRequestHandlers", types.Select(static type => type.RequestLines));
        builder.AppendLine();
        AppendMethod(builder, "AutoRegisterStreamHandlers", types.Select(static type => type.StreamLines));
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendMethod(StringBuilder builder, string name, IEnumerable<string> bodies)
    {
        builder.Append("        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(name)
            .AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        builder.AppendLine("        {");
        foreach (var body in bodies)
        {
            builder.Append(body);
        }

        builder.AppendLine("            return services;");
        builder.AppendLine("        }");
    }
}
