<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>MediatRR</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="System.Threading.Channels" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediatRR.Contract\MediatRR.Contract.csproj" />
    <ProjectReference Include="..\MediatRR.Generators\MediatRR.Generators.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\MediatRR.Generators\bin\$(Configuration)\netstandard2.0\MediatRR.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MediatRR.Tests" />
  </ItemGroup>
</Project>
