<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <!-- Package metadata -->
    <PackageId>MediatRR</PackageId>
    <!-- Include the DLL as both runtime library and analyzer -->
    <IncludeBuildOutput>true</IncludeBuildOutput>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="F:\source\repos\MediatRR\MediatRR\mediatrr.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="System.Threading.Channels" Version="10.0.9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MediatRR.Contract\MediatRR.Contract.csproj" />
  </ItemGroup>
 
  <ItemGroup>
    <InternalsVisibleTo Include="MediatRR.Tests" />
  </ItemGroup>
</Project>